version: "3.3"
services:
  nies:
    build:
      context: .
      dockerfile: Dockerfile
    image: nepolin/api_predictions_and_bets
    ports:
      - "8383:80"
    volumes:
      - $PWD/tests/data/:/app/data/
